<?php

namespace JEU\PlatformBundle\Repository;

/**
 * DefausseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefausseRepository extends \Doctrine\ORM\EntityRepository
{
}
