<?php

namespace JEU\PlatformBundle\Repository;

/**
 * PiocheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiocheRepository extends \Doctrine\ORM\EntityRepository
{
}
